service:
  name: gestalt-hello-world
provider:
  name: gestalt
  context: /engineering/jay-bee/qa
  laser: laser
  api: test
functions:
  hello-world:
    description: "This is a lambda that returns hello world"
    runtime: nodejs
    handler: hello
    package-url: https://raw.githubusercontent.com/GalacticFog/serverless-gestalt-hello-world/master/handler.js
    compressed: false
    headers:
      Accept: text/plain
      Content-Type: application/json
    endpoint:
      path: /hello-world
      methods: ['GET']
      secure: false
      synchronous: true
      rate-limit: 60
    timeout: 60
    memory: 128
    cpus: 0.1
    public: true
    variables:
      GREETING: Greetings from Galactic Fog!
plugins: 
  - serverless-gestalt
